"""empty message

Revision ID: 18d5d3dc75d8
Revises: 922fe8fb673c
Create Date: 2022-08-24 21:51:49.136433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d5d3dc75d8'
down_revision = '922fe8fb673c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('contato', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_id'), 'cliente', ['id'], unique=False)
    op.create_index(op.f('ix_cliente_nome'), 'cliente', ['nome'], unique=False)
    op.drop_index('ix_Cliente_id', table_name='Cliente')
    op.drop_index('ix_Cliente_nome', table_name='Cliente')
    op.drop_table('Cliente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cliente',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=True),
    sa.Column('contato', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Cliente_nome', 'Cliente', ['nome'], unique=False)
    op.create_index('ix_Cliente_id', 'Cliente', ['id'], unique=False)
    op.drop_index(op.f('ix_cliente_nome'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_id'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
