"""abc

Revision ID: 45cbd68b7fee
Revises: 
Create Date: 2022-08-14 23:57:49.849910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cbd68b7fee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_contrato_id'), 'tipo_contrato', ['id'], unique=False)
    op.create_index(op.f('ix_tipo_contrato_nome'), 'tipo_contrato', ['nome'], unique=False)
    op.create_table('zona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zona_id'), 'zona', ['id'], unique=False)
    op.create_index(op.f('ix_zona_nome'), 'zona', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zona_nome'), table_name='zona')
    op.drop_index(op.f('ix_zona_id'), table_name='zona')
    op.drop_table('zona')
    op.drop_index(op.f('ix_tipo_contrato_nome'), table_name='tipo_contrato')
    op.drop_index(op.f('ix_tipo_contrato_id'), table_name='tipo_contrato')
    op.drop_table('tipo_contrato')
    # ### end Alembic commands ###
