"""add tipo contrato

Revision ID: 50dfe86b5b59
Revises: 8783d032b533
Create Date: 2022-08-11 23:17:10.458759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50dfe86b5b59'
down_revision = '8783d032b533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.drop_table('tipo_contrato')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_contrato',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('nome', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
