"""teste

Revision ID: 73d44783c3d0
Revises: 71cfa2ee5a8b
Create Date: 2022-08-11 23:13:00.484607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d44783c3d0'
down_revision = '71cfa2ee5a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zona_id'), 'zona', ['id'], unique=False)
    op.create_index(op.f('ix_zona_nome'), 'zona', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zona_nome'), table_name='zona')
    op.drop_index(op.f('ix_zona_id'), table_name='zona')
    op.drop_table('zona')
    # ### end Alembic commands ###
