"""empty message

Revision ID: 92e201ec76e3
Revises: e0fa59a980a1
Create Date: 2022-09-03 20:25:14.844263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e201ec76e3'
down_revision = 'e0fa59a980a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamado', schema=None) as batch_op:
        batch_op.create_foreign_key("None", 'status_chamado', ['status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamado', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
