"""empty message

Revision ID: a5e73e42f80b
Revises: 92e201ec76e3
Create Date: 2022-09-03 20:59:41.928525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e73e42f80b'
down_revision = '92e201ec76e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
