"""empty message

Revision ID: bcdcb9723524
Revises: 18d5d3dc75d8
Create Date: 2022-08-28 22:33:45.075446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdcb9723524'
down_revision = '18d5d3dc75d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_cargo'), 'cargo', ['cargo'], unique=False)
    op.create_index(op.f('ix_cargo_id'), 'cargo', ['id'], unique=False)
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('contato', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_id'), 'cliente', ['id'], unique=False)
    op.create_index(op.f('ix_cliente_nome'), 'cliente', ['nome'], unique=False)
    op.create_table('usuario',
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.Column('zona', sa.String(), nullable=True),
    sa.Column('cargo_id', sa.String(), nullable=True),
    sa.Column('salario', sa.String(), nullable=True),
    sa.Column('is_adm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_index(op.f('ix_usuario_cargo_id'), 'usuario', ['cargo_id'], unique=False)
    op.create_index(op.f('ix_usuario_cpf'), 'usuario', ['cpf'], unique=False)
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=False)
    op.create_index(op.f('ix_usuario_matricula'), 'usuario', ['matricula'], unique=False)
    op.create_index(op.f('ix_usuario_nome'), 'usuario', ['nome'], unique=False)
    op.create_index(op.f('ix_usuario_salario'), 'usuario', ['salario'], unique=False)
    op.create_index(op.f('ix_usuario_senha'), 'usuario', ['senha'], unique=False)
    op.create_index(op.f('ix_usuario_telefone'), 'usuario', ['telefone'], unique=False)
    op.create_index(op.f('ix_usuario_zona'), 'usuario', ['zona'], unique=False)
    op.create_index(op.f('ix_usuario_zona_id'), 'usuario', ['zona_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_zona_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_zona'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_telefone'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_senha'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_salario'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_nome'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_matricula'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_cpf'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_cargo_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_cliente_nome'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_id'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_cargo_id'), table_name='cargo')
    op.drop_index(op.f('ix_cargo_cargo'), table_name='cargo')
    op.drop_table('cargo')
    # ### end Alembic commands ###
