"""empty message

Revision ID: e0fa59a980a1
Revises: 
Create Date: 2022-09-03 18:10:58.084173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0fa59a980a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_cargo'), 'cargo', ['cargo'], unique=False)
    op.create_index(op.f('ix_cargo_id'), 'cargo', ['id'], unique=False)
    op.create_table('natureza_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_natureza_empresa_id'), 'natureza_empresa', ['id'], unique=False)
    op.create_index(op.f('ix_natureza_empresa_nome'), 'natureza_empresa', ['nome'], unique=False)
    op.create_table('tipo_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_contrato_id'), 'tipo_contrato', ['id'], unique=False)
    op.create_index(op.f('ix_tipo_contrato_nome'), 'tipo_contrato', ['nome'], unique=False)
    op.create_table('tipo_equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_equipamento_id'), 'tipo_equipamento', ['id'], unique=False)
    op.create_index(op.f('ix_tipo_equipamento_nome'), 'tipo_equipamento', ['nome'], unique=False)
    op.create_table('tipo_manutencao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_manutencao_id'), 'tipo_manutencao', ['id'], unique=False)
    op.create_index(op.f('ix_tipo_manutencao_nome'), 'tipo_manutencao', ['nome'], unique=False)
    op.create_table('zona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zona_id'), 'zona', ['id'], unique=False)
    op.create_index(op.f('ix_zona_nome'), 'zona', ['nome'], unique=False)
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('contato', sa.String(), nullable=True),
    sa.Column('natureza_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['natureza_id'], ['natureza_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_id'), 'cliente', ['id'], unique=False)
    op.create_index(op.f('ix_cliente_natureza_id'), 'cliente', ['natureza_id'], unique=False)
    op.create_index(op.f('ix_cliente_nome'), 'cliente', ['nome'], unique=False)
    op.create_table('usuario',
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('salario', sa.String(), nullable=True),
    sa.Column('is_adm', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['zona_id'], ['zona.id'], ),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_index(op.f('ix_usuario_cargo_id'), 'usuario', ['cargo_id'], unique=False)
    op.create_index(op.f('ix_usuario_cidade'), 'usuario', ['cidade'], unique=False)
    op.create_index(op.f('ix_usuario_cpf'), 'usuario', ['cpf'], unique=False)
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=False)
    op.create_index(op.f('ix_usuario_matricula'), 'usuario', ['matricula'], unique=False)
    op.create_index(op.f('ix_usuario_nome'), 'usuario', ['nome'], unique=False)
    op.create_index(op.f('ix_usuario_salario'), 'usuario', ['salario'], unique=False)
    op.create_index(op.f('ix_usuario_senha'), 'usuario', ['senha'], unique=False)
    op.create_index(op.f('ix_usuario_telefone'), 'usuario', ['telefone'], unique=False)
    op.create_index(op.f('ix_usuario_zona_id'), 'usuario', ['zona_id'], unique=False)
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('vencimento', sa.String(), nullable=True),
    sa.Column('valor_contrato', sa.String(), nullable=True),
    sa.Column('contato', sa.String(), nullable=True),
    sa.Column('responsavel_nome', sa.String(), nullable=True),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['zona_id'], ['zona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contrato_cliente_id'), 'contrato', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_contrato_contato'), 'contrato', ['contato'], unique=False)
    op.create_index(op.f('ix_contrato_id'), 'contrato', ['id'], unique=False)
    op.create_index(op.f('ix_contrato_valor_contrato'), 'contrato', ['valor_contrato'], unique=False)
    op.create_index(op.f('ix_contrato_vencimento'), 'contrato', ['vencimento'], unique=False)
    op.create_index(op.f('ix_contrato_zona_id'), 'contrato', ['zona_id'], unique=False)
    op.create_table('equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('num_serie', sa.String(), nullable=True),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('local', sa.String(), nullable=True),
    sa.Column('capacidade', sa.String(), nullable=True),
    sa.Column('velocidade', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_equipamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipamento_contrato_id'), 'equipamento', ['contrato_id'], unique=False)
    op.create_index(op.f('ix_equipamento_id'), 'equipamento', ['id'], unique=False)
    op.create_index(op.f('ix_equipamento_local'), 'equipamento', ['local'], unique=False)
    op.create_index(op.f('ix_equipamento_marca'), 'equipamento', ['marca'], unique=False)
    op.create_index(op.f('ix_equipamento_modelo'), 'equipamento', ['modelo'], unique=False)
    op.create_index(op.f('ix_equipamento_num_serie'), 'equipamento', ['num_serie'], unique=False)
    op.create_index(op.f('ix_equipamento_tipo_id'), 'equipamento', ['tipo_id'], unique=False)
    op.create_table('chamado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('equipamento_id', sa.Integer(), nullable=True),
    sa.Column('tipo_manutencao_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(), nullable=True),
    sa.Column('data_hora_abertura', sa.String(), nullable=True),
    sa.Column('data_hora_inicio', sa.String(), nullable=True),
    sa.Column('data_hora_fim', sa.String(), nullable=True),
    sa.Column('tecnico_matricula', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamento.id'], ),
    sa.ForeignKeyConstraint(['tecnico_matricula'], ['usuario.matricula'], ),
    sa.ForeignKeyConstraint(['tipo_manutencao_id'], ['tipo_manutencao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamado_acao'), 'chamado', ['acao'], unique=False)
    op.create_index(op.f('ix_chamado_cliente_id'), 'chamado', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_chamado_data_hora_abertura'), 'chamado', ['data_hora_abertura'], unique=False)
    op.create_index(op.f('ix_chamado_data_hora_fim'), 'chamado', ['data_hora_fim'], unique=False)
    op.create_index(op.f('ix_chamado_data_hora_inicio'), 'chamado', ['data_hora_inicio'], unique=False)
    op.create_index(op.f('ix_chamado_equipamento_id'), 'chamado', ['equipamento_id'], unique=False)
    op.create_index(op.f('ix_chamado_id'), 'chamado', ['id'], unique=False)
    op.create_index(op.f('ix_chamado_observacao'), 'chamado', ['observacao'], unique=False)
    op.create_index(op.f('ix_chamado_tecnico_matricula'), 'chamado', ['tecnico_matricula'], unique=False)
    op.create_index(op.f('ix_chamado_tipo_manutencao_id'), 'chamado', ['tipo_manutencao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chamado_tipo_manutencao_id'), table_name='chamado')
    op.drop_index(op.f('ix_chamado_tecnico_matricula'), table_name='chamado')
    op.drop_index(op.f('ix_chamado_observacao'), table_name='chamado')
    op.drop_index(op.f('ix_chamado_id'), table_name='chamado')
    op.drop_index(op.f('ix_chamado_equipamento_id'), table_name='chamado')
    op.drop_index(op.f('ix_chamado_data_hora_inicio'), table_name='chamado')
    op.drop_index(op.f('ix_chamado_data_hora_fim'), table_name='chamado')
    op.drop_index(op.f('ix_chamado_data_hora_abertura'), table_name='chamado')
    op.drop_index(op.f('ix_chamado_cliente_id'), table_name='chamado')
    op.drop_index(op.f('ix_chamado_acao'), table_name='chamado')
    op.drop_table('chamado')
    op.drop_index(op.f('ix_equipamento_tipo_id'), table_name='equipamento')
    op.drop_index(op.f('ix_equipamento_num_serie'), table_name='equipamento')
    op.drop_index(op.f('ix_equipamento_modelo'), table_name='equipamento')
    op.drop_index(op.f('ix_equipamento_marca'), table_name='equipamento')
    op.drop_index(op.f('ix_equipamento_local'), table_name='equipamento')
    op.drop_index(op.f('ix_equipamento_id'), table_name='equipamento')
    op.drop_index(op.f('ix_equipamento_contrato_id'), table_name='equipamento')
    op.drop_table('equipamento')
    op.drop_index(op.f('ix_contrato_zona_id'), table_name='contrato')
    op.drop_index(op.f('ix_contrato_vencimento'), table_name='contrato')
    op.drop_index(op.f('ix_contrato_valor_contrato'), table_name='contrato')
    op.drop_index(op.f('ix_contrato_id'), table_name='contrato')
    op.drop_index(op.f('ix_contrato_contato'), table_name='contrato')
    op.drop_index(op.f('ix_contrato_cliente_id'), table_name='contrato')
    op.drop_table('contrato')
    op.drop_index(op.f('ix_usuario_zona_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_telefone'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_senha'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_salario'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_nome'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_matricula'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_cpf'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_cidade'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_cargo_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_cliente_nome'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_natureza_id'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_id'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_zona_nome'), table_name='zona')
    op.drop_index(op.f('ix_zona_id'), table_name='zona')
    op.drop_table('zona')
    op.drop_index(op.f('ix_tipo_manutencao_nome'), table_name='tipo_manutencao')
    op.drop_index(op.f('ix_tipo_manutencao_id'), table_name='tipo_manutencao')
    op.drop_table('tipo_manutencao')
    op.drop_index(op.f('ix_tipo_equipamento_nome'), table_name='tipo_equipamento')
    op.drop_index(op.f('ix_tipo_equipamento_id'), table_name='tipo_equipamento')
    op.drop_table('tipo_equipamento')
    op.drop_index(op.f('ix_tipo_contrato_nome'), table_name='tipo_contrato')
    op.drop_index(op.f('ix_tipo_contrato_id'), table_name='tipo_contrato')
    op.drop_table('tipo_contrato')
    op.drop_index(op.f('ix_natureza_empresa_nome'), table_name='natureza_empresa')
    op.drop_index(op.f('ix_natureza_empresa_id'), table_name='natureza_empresa')
    op.drop_table('natureza_empresa')
    op.drop_index(op.f('ix_cargo_id'), table_name='cargo')
    op.drop_index(op.f('ix_cargo_cargo'), table_name='cargo')
    op.drop_table('cargo')
    # ### end Alembic commands ###
